//Source code generated by AppGPT (www.appgpt.tech)
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react()],
  base: '/a3ab12c41/',
  build: {
    outDir: '.output/a3ab12c41',
    emptyOutDir: true,
  },
  server: {
    host: true,
    strictPort: true,
    port: 5173,
  },
});
