//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Policies')
export class PoliciesEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  policyTitle: string;

  @Column('text', { nullable: true })
  policyDescription: string;

  @Column('date', { nullable: true })
  implementationDate: Date;

  @Column('text', { nullable: true })
  policyObjectives: string;

  @Column('text', { nullable: true })
  keyFeatures: string;
}
