//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const PoliciesTitle = () => {
  const record = useRecordContext();
  return <span>Policies {record ? `"${record.policyTitle}"` : ''}</span>;
};

export const PoliciesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <TextField source="policyTitle" />
      <TextField source="policyDescription" />
      <DateField source="implementationDate" />
      <TextField source="policyObjectives" />
      <TextField source="keyFeatures" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const PoliciesEdit = () => (
  <Edit title={<PoliciesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="policyTitle" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="policyDescription" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="implementationDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="policyObjectives" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="keyFeatures" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const PoliciesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <TextInput source="policyTitle" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="policyDescription" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="implementationDate" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="policyObjectives" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="keyFeatures" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
];
