//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    Policies: [
      {
        policyTitle: 'policyTitle 1',
        policyDescription: 'policyDescription 1',
        implementationDate: '2023-08-05T11:38:50.353Z',
        policyObjectives: 'policyObjectives 1',
        keyFeatures: 'keyFeatures 1',
        id: 88,
      },
      {
        policyTitle: 'policyTitle 2',
        policyDescription: 'policyDescription 2',
        implementationDate: '2025-02-16T18:18:31.092Z',
        policyObjectives: 'policyObjectives 2',
        keyFeatures: 'keyFeatures 2',
        id: 21,
      },
      {
        policyTitle: 'policyTitle 3',
        policyDescription: 'policyDescription 3',
        implementationDate: '2024-04-29T23:35:11.904Z',
        policyObjectives: 'policyObjectives 3',
        keyFeatures: 'keyFeatures 3',
        id: 60,
      },
      {
        policyTitle: 'policyTitle 4',
        policyDescription: 'policyDescription 4',
        implementationDate: '2023-07-16T18:06:01.010Z',
        policyObjectives: 'policyObjectives 4',
        keyFeatures: 'keyFeatures 4',
        id: 94,
      },
      {
        policyTitle: 'policyTitle 5',
        policyDescription: 'policyDescription 5',
        implementationDate: '2024-02-13T05:10:42.393Z',
        policyObjectives: 'policyObjectives 5',
        keyFeatures: 'keyFeatures 5',
        id: 11,
      },
    ],
  },
};
export default data;
