//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    Policies: {
      name: 'Policies',
      fields: {
        policyTitle: 'Policy Title',
        policyDescription: 'Policy Description',
        implementationDate: 'Implementation Date',
        policyObjectives: 'Policy Objectives',
        keyFeatures: 'Key Features',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    Policies: {
      name: 'Policies (fr)',
      fields: {
        policyTitle: 'Policy Title (fr)',
        policyDescription: 'Policy Description (fr)',
        implementationDate: 'Implementation Date (fr)',
        policyObjectives: 'Policy Objectives (fr)',
        keyFeatures: 'Key Features (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
